project:
  type: website
  output-dir: _site

website:
  title: "Docs in Motion"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Articles
        menu:
          - docs/articles/article-1.qmd
          - docs/articles/article-2.qmd
          - docs/articles/article-3.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Documentation"
        contents:
          - docs/articles/article-1.qmd
          - docs/articles/article-2.qmd
          - docs/articles/article-3.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true

execute:
  freeze: auto
