project:
  type: website
  output-dir: _site

website:
  title: "Docs in Motion"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Articles
        menu:
          - docs/articles/article-1.qmd
          - docs/articles/article-2.qmd
          - docs/articles/article-3.qmd

format:
  html:
    theme: none
    css: styles.css
    toc: false
    code-copy: false

execute:
  freeze: auto
